# ONVIF-NATS Gateway Application Configuration

# NATS Configuration
nats:
  url: "nats://localhost:4222"
  username: ""
  password: ""
  connection_timeout: 10s
  reconnect_wait: 2s
  max_reconnects: 5

# ONVIF Configuration
onvif:
  discovery_timeout: 30s
  event_pull_timeout: 60s
  subscription_renew: 300s  # 5 minutes
  enable_discovery: true
  worker_count: 3
  event_buffer_size: 1000

# HTTP API Configuration
http:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s

# Logging Configuration
logging:
  level: "info"  # debug, info, warn, error, fatal
  format: "json" # json, text
  component: "onvif-gateway"
